env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - eslint-config-prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - ./tsconfig.app.json
    - ./tsconfig.node.json
  ecmaVersion: latest
  sourceType: module
rules:
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/triple-slash-reference': off # for Vite fix
  '@typescript-eslint/consistent-type-assertions': off
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript: true
    node: true
    alias:
      map:
        - ['@', './src']
        - ['~', './node_modules']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
  vite:
    configPath: ./vite.config.ts
